.TH "gde2-about-me" "1" 

.SH "NAME" 
gde2-about-me \(em is a control center applet. 

.SH "SYNOPSIS" 
.PP 
\fBgde2-about-me\fR 

.SH "DESCRIPTION" 
.PP 
GDE2 About Me is a control center applet to set user information.
.PP
It allows one to change user password and set user avatar image (~/.face file). 

.SH "AUTHOR" 
.PP 
This manual page was written by Stefano Karapetsas <stefano@karapetsas.com>.
